apiVersion: v1
kind: pod
metadata:
  name: pod1
  namespace: facebook
spec:
  containers:
  - name: web
    image: httpd
    ports:
    - containerPort: 80
  - name: db
    image: mysql
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: ranga123
      
